### ISSUE TITLE
Cannot find name 'ImageUploadModule'.   

### ISSUE THREAD

**Issue by svsh227** [aberezkin/ng2-image-upload#10]
Error: Cannot find name 'ImageUploadModule'. 

**app.module.ts:**

@NgModule({
  bootstrap: [ AppComponent ],
  declarations: [
    AppComponent,
    AboutComponent,
    HomeComponent,
    NoContentComponent,
    XLargeDirective
  ],
  imports: [ // import Angular's modules
    BrowserModule,
    FormsModule,
    HttpModule,
    **ImageUploadModule.forRoot(),**
    RouterModule.forRoot(ROUTES, { useHash: true, preloadingStrategy: PreloadAllModules })
  ],
  providers: [ // expose our Services and Providers into Angular's dependency injection
    ENV_PROVIDERS,
    APP_PROVIDERS
  ]
})

Why it is throwing "Error: Cannot find name 'ImageUploadModule'. "

**Comment by aberezkin** [comment]
Did you import it with `import {ImageUploadModule} from "angular2-image-upload";`?

**Comment by neuthral** [comment]
Hi, i got this to work with adding these to systemjs.config.js:

map: {
...
**'angular2-image-upload':     'node_modules/angular2-image-upload'**
...
packages: {
...
**'angular2-image-upload': {
        main: 'index.js',
        defaultExtension: 'js'
      }**
