### ISSUE TITLE
Default branch

### ISSUE THREAD

**Issue by UncleDave** [aberezkin/ng2-image-upload#103]
Should probably be master - if a user arrives at the repo homepage they see the development demo and development readme, this is giving them the wrong API information as it is not yet released.

**Comment by aberezkin** [comment]
No, they see only development README, the source code for demo page is taken from the master branch. We can just remove API reference from README and leave something like "See demo page for API reference". So can still take advantage of GitHub resolving issues automatically on PR merge.

**Comment by UncleDave** [comment]
Alright, lets move the readme to the demo so we don't lose any information.
