### ISSUE TITLE
Custom formData

### ISSUE THREAD

**Issue by cornelius-agrippa** [aberezkin/ng2-image-upload#105]
Hello,

Is it possible to specify custom or additional formData? 

I saw in the documentation that the query has a single field called "image". But I'm working with a closed API that accepts a field called "file" instead. Additionally I need to send other parameters with this request. Is this possible?

Thank you,
My best regards

**Comment by aberezkin** [comment]
We can provide such interface in `UploadMetadata`, can't we?

**Comment by UncleDave** [comment]
That is what I was thinking, yes.

**Comment by et-taousy** [comment]
If you want to add another parameters you can send them on url?param1=val1...

**Comment by raydvard** [comment]
Have you guys added this enhancement yet ? If so, then please add documentation on that.
I can see in the release check list that it is done, but can't find any documentation on that.
1.0.0 #102
