### ISSUE TITLE
Release Plan

### ISSUE THREAD

**Issue by ViktorPlohl** [aberezkin/ng2-image-upload#106]
When is the new version coming out to npm?

**Comment by UncleDave** [comment]
When the checklist in #102 is complete. Is there anything in particular you're eager to get your hands on?

**Comment by kwafoawua** [comment]
I hope the release comes out soon. I want to change Clear button text. Is there any way to get the latest version of this to use it in my site?

**Comment by UncleDave** [comment]
In the short term you can do the following, assuming you're using `npm` to manage your dependencies:

1. Clone this repo
2. Checkout the development branch with `git checkout development`
3. Run the command `npm run build`
4. If all is well you should now be able to run `npm pack` - this will prdoce a .tgz which can be installed with npm.
5. Copy the .tgz to your project's root directory and remember to check it into your source control.
6. Assuming the latest version of npm, you can install the package with `npm install ./angular2-image-upload-0.6.5.tgz`

**Comment by kwafoawua** [comment]
Thank you very much for the fast answer! I'll try it tomorrow!!
