### ISSUE TITLE
Module.forRoot

### ISSUE THREAD

**Issue by jakerabjohns15** [aberezkin/ng2-image-upload#108]
I am currently trying to integrate your library as per the instructions in the readme, however I am having trouble even importing your module. I am currently trying to use .forRoot as you specify, however a brief glance at your code in my node_modules confirms you do not have a forRoot method, which my TSC then barfs at. Is it possible to get your current library from NPM, or could you provide some documentation for the old version? I would really rather not fork your repo just for this. 

Thanks.

**Comment by UncleDave** [comment]
The currently released version on npm (0.6.4) does have `ImageUploadModule.forRoot`

**Comment by jakerabjohns15** [comment]
Gosh dangit, I just checked the package.json inside my node_modules and its ng2-image-upload. Too many similarly named libaries, sorry my bad :) Thanks for the rapid response.

**Comment by UncleDave** [comment]
Easy mistake, sadly the npm package is not named the same as the repo.
