### ISSUE TITLE
Upload and reactive forms

### ISSUE THREAD

**Issue by CrikoC** [aberezkin/ng2-image-upload#109]
Is it possible to add the url value in a reactive form, so that i can add an image in a post inside my database?

**Comment by UncleDave** [comment]
Have no experience with reactive forms - can anyone answer this?

**Comment by aberezkin** [comment]
Do you want your image to be sent with other data (i.e. post title, the text itself)?

**Comment by CrikoC** [comment]
Yes that is exactly how i wish to send an image so that i can display it afterwards for each new post entry.

`this.addPostForm = new FormGroup({
            'name':         new FormControl(null, Validators.required),
            'body':         new FormControl(null, Validators.required),
            'author':       new FormControl(this.username, Validators.required),
            'image':        new FormControl(null),
            'category_id':  new FormControl(this.category_id, Validators.required),
            'published_at': new FormControl(new Date, Validators.required),
        });`

**Comment by aberezkin** [comment]
You can do the following.

1. Specify no URL in the image-upload component.
2. Accumulate images from component in an array using `uploadFinished` method.
3. Set `images` field in `this.addPostForm.value` manually
4. Send everything in on request
