### ISSUE TITLE
nativeError : Template parse errors: Can't bind to 'url' since it isn't a known property of 'image-upload'.

### ISSUE THREAD

**Issue by svsh227** [aberezkin/ng2-image-upload#11]
nativeError:Error: Template parse errors: Can't bind to 'url' since it isn't a known property of 'image-upload'.
 
1. If 'image-upload' is an Angular component and it has 'url' input, then verify that it is part of this module. 
2. If 'image-upload' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 (" <image-upload [ERROR ->]
[url]="'example.com/images/upload'" 
[buttonCaption]="'Select Images!'" 
[dropBoxMessage]="'Drop yo"): HomeComponent@36:2 Can't bind to 'buttonCaption' since it isn't a known property of 'image-upload'.
 1. If 'image-upload' is an Angular component and it has 'buttonCaption' input, then verify that it is part of this module.
 2. If 'image-upload' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. (" <image-upload [url]="'example.com/images/upload'" [ERROR ->]

[buttonCaption]="'Select Images!'" 

[dropBoxMessage]="'Drop your images here!'" (onFileUploadFinis"): HomeComponent@37:2 Can't bind to 'dropBoxMessage' since it isn't a known property of 'image-upload'.

 1. If 'image-upload' is an Angular component and it has 'dropBoxMessage' input, then verify that it is part of this module.
 2. If 'image-upload' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. (" [url]="'example.com/images/upload'" 

[buttonCaption]="'Select Images!'" [ERROR ->]

[dropBoxMessage]="'Drop your images here!'" (onFileUploadFinish)="imageUploaded($event)" (onRemov"): HomeComponent@38:2 'image-upload' is not a known element: 1. If 'image-upload' is an Angular component, then verify that it is part of this module. 2. If 'image-upload' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 (" [ERROR ->]<image-upload [url]="'example.com/images/upload'" [buttonCaption]="'Select Images!'" "): HomeComponent@35:0 at SyntaxError.BaseError [as constructor] (http://127.0.0.1:3000/vendor.bundle.js:5206:27) [<root>] at new SyntaxError (http://127.0.0.1:3000/vendor.bundle.js:5454:16) [<root>] at TemplateParser.parse (http://127.0.0.1:3000/vendor.bundle.js:17079:19) [<root>] at JitCompiler._compileTemplate (http://127.0.0.1:3000/vendor.bundle.js:48132:68) [<root>] at http://127.0.0.1:3000/vendor.bundle.js:48015:62 [<root>] at Set.forEach (native) [<root>] at JitCompiler._compileComponents (http://127.0.0.1:3000/vendor.bundle.js:48015:19) [<root>] at createResult (http://127.0.0.1:3000/vendor.bundle.js:47898:19) [<root>] at Zone.run (http://127.0.0.1:3000/polyfills.bundle.js:15367:43) [<root> => <root>] at http://127.0.0.1:3000/polyfills.bundle.js:15774:57 [<root>] at Zone.runTask (http://127.0.0.1:3000/polyfills.bundle.js:15405:47) [<root> => <root>] at drainMicroTaskQueue (http://127.0.0.1:3000/polyfills.bundle.js:15672:35) [<root>] at HTMLDocument.ZoneTask.invoke (http://127.0.0.1:3000/polyfills.bundle.js:15603:25) [<root>

**Comment by svsh227** [comment]
Please help me .

**Comment by aberezkin** [comment]
Did you resolve #10 because I think that the root of the problem is that you didn't import the module.
