### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by deinega** [aberezkin/ng2-image-upload#118]
When I am trying to build for production it it says:

ERROR in SOME_FOLDER/src/$$_gendir/node_modules/angular2-image-upload/lib/image-upload/image-upload.component.ngfactory.ts (559,18): Property 'inputElement' is private and only accessible within class 'ImageUploadComponent'

**Comment by UncleDave** [comment]
Ensure you're up to date - 0.6.6

**Comment by deinega** [comment]
How can I get 0.6.6?

Development version is 0.6.5:
https://github.com/aberezkin/ng2-image-upload/blob/development/package.json

Also, is dynamic css styling supposes to go to 0.6.6?

**Comment by aberezkin** [comment]
@deinega just do `npm install angular2-image-upload@0.6.6`

**Comment by UncleDave** [comment]
Due to an error when publishing 0.6.6 is actually 0.6.5 as far as the changelog is concerned, but the version number change isn't in the repo.

**Comment by ARadauer** [comment]
Same here, we updated to 0.6.6 but we are still receiving this error:
/$$_gendir/node_modules/angular2-image-upload/lib/image-upload/image-upload.component.ngfactory.ts (559,18): Property 'inputElement' is private and only accessible within class 'ImageUploadComponent'.

changelog.md shows its 0.6.5

Thanks!

**Comment by UncleDave** [comment]
I'm unable to recreate this. Try removing `node_modules/angular2-image-upload` then installing it again.

If that fails you're going to have to show us your usage or provide a repo that reproduces the issue.
