### ISSUE TITLE
customStyle is not applied

### ISSUE THREAD

**Issue by MBelkhechine** [aberezkin/ng2-image-upload#124]
Using the attribute **[style]="'customStyle'"** and declaring a customStyle in my component does not change the look and feel of the image-upload section.
```javascript
export class FooComponent {
...
customStyle = {
  selectButton: {
    "color": "white",
    "background-color": "purple",
  },
  clearButton: {
    "color": "white",
    "background-color": "yellow",
  },
  layout: {
    "background-color": "black",
    "color": "red",
    "font-size": "15px",
  },
  previewPanel: {
    "background-color": "red",
  }
}
...
}
```
**<image-upload [style]="'customStyle'" [max]="2" [extensions]="['jpeg','png']" (onFileUploadFinish)="onUploadFinished($event)"></image-upload>**

None of the previously css rules are loaded by the app.

**Comment by UncleDave** [comment]
This feature is not yet released.
Github is currently displaying the readme from the development branch, whereas the latest release is on master, sorry about that, there's an issue open to move the readme content out to the demo page instead - #104.

**Comment by MBelkhechine** [comment]
Thank you for your response.
Is there any other way to change the CSS? 
I tried to do some changes in the file image-upload.component.css but with no success.

**Comment by UncleDave** [comment]
You should be able to target the library's elements with standard CSS selectors.

e.g.

````
image-upload label.upload.button {
    background-color: red;
}
````
