### ISSUE TITLE
Differentiate between the events of Clear click and Remove click

### ISSUE THREAD

**Issue by MBelkhechine** [aberezkin/ng2-image-upload#125]
Hi,

is there any way to distinguish between the event of Clear click and the event of Remove click?

I need this to handle images deletion correctly. In the case where Clear is clicked I have to remove all the images and in case of Remove I need to delete only the selected one.

**Comment by UncleDave** [comment]
Both clear and remove emit the same event - `onRemove`.

I believe this should work for your use case as when clear is clicked it simply emits `onRemove` once for each image and passes the `FileHolder` through as the `$event`.
