### ISSUE TITLE
[url]="'example.com/images/upload'" - this is the url which can handle POST queries with multipart/form-data Content-Type. The query has a single field called image

### ISSUE THREAD

**Issue by scorobogaci** [aberezkin/ng2-image-upload#126]
Provide an way please to specify query name .
Requires work on the server side to change handler endpoint

**Comment by scorobogaci** [comment]
`public postImage(url: string, image: File, headers?: Headers | { [name: string]: any }, partName: string = 'image', customFormData?: { [name: string]: any }, withCredentials?: boolean): Observable<Response>`

Why you're hardicoding partName ?

**Comment by UncleDave** [comment]
This is passed from the component and defaulted to "image" - try setting the `partName` attribute to whatever you want. For example:

`<image-upload-component partName="file"></image-upload-component>`

**Comment by scorobogaci** [comment]
`        <image-upload [url]="'http://192.168.99.100/backend.php'"
                      [partName]="'postimage'"
                      (onFileUploadFinish)="uploadImage($event)"
                      (onRemove)="deleteImage($event)">
        </image-upload>`

Even that the response seems to be ok 
`"{"status":"OK","type":"png","hash":"slj7u1qavq.png","url":"http:\/\/192.168.99.100\/slj7u1qavq.png","domain":"http:\/\/192.168.99.100"}"`

In upload folder in container I cannot see the image, where is the problem?
Can you help me with this?

**Comment by scorobogaci** [comment]
Thank you for help .I'm new to angular world :) Thank you
