### ISSUE TITLE
Headers not being sent

### ISSUE THREAD

**Issue by adskiremote** [aberezkin/ng2-image-upload#127]
Hi I've used the [headers] binding but no headers are being sent in the request.
I used the demo and included in my Angular app but still not included.

Many thanks

**Comment by UncleDave** [comment]
I suspect you're a victim of our default branch issue.
Our default branch is `development` - this is the latest stuff and is not yet released, however github will display the readme from this branch by default. One of the unreleased changes is a header format change, please see the readme from the `master` [here](https://github.com/aberezkin/ng2-image-upload/tree/master).

#104 will resolve this confusing structure some day.

**Comment by adskiremote** [comment]
Fixed thank you.  For anyone else headers should be formatted like this (depending on your auth setup)

`this.myHeaders = [{
    header: 'Authorization', value: 'Bearer ' + this.token
  }];`
