### ISSUE TITLE
Possible to trigger clear image function programmatically ?

### ISSUE THREAD

**Issue by wwyeong** [aberezkin/ng2-image-upload#128]
Hi, i like to clear the uploaded image from inside , is't possible to done that?

**Comment by UncleDave** [comment]
You can try the following in the component that owns the `image-upload` component:

    import { ImageUploadComponent } from 'angular2-image-upload/lib/image-upload/image-upload.component';

    @ViewChild(ImageUploadComponent) imageUploadComponent: ImageUploadComponent;

    clearUploadedImages() {
      imageUploadComponent.deleteAll();
    }

**Comment by wwyeong** [comment]
You saved my day 💯 . Thank you!

**Comment by souflam** [comment]
this is was useful, one thing you must add "this" to imageUploadComponent.deleteAll()
this.imageUploadComponent.deleteAll()

**Comment by zeeshancb** [comment]
not working but giving any error too

**Comment by zeeshancb** [comment]
not working but not giving any error too,this.imageUplodeComponent.deleteFile(this.imageUploadComponent.files[0]) did half of the job for me
