### ISSUE TITLE
 No provider for FileHolder!

### ISSUE THREAD

**Issue by mayurbais** [aberezkin/ng2-image-upload#132]
I added this component to project and when used, getting this error

```
ERROR Error: No provider for FileHolder!
    at injectionError (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.bundle.js:39), <anonymous>:1373:90)
    at noProviderError (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.bundle.js:39), <anonymous>:1411:12)
    at ReflectiveInjector_._throwOrNull (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.bundle.js:39), <anonymous>:2853:19)
    at ReflectiveInjector_._getByKeyDefault (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.bundle.js:39), <anonymous>:2892:25)
```

**Comment by UncleDave** [comment]
Please show your usage. The error indicates you're trying to inject `FileHolder`, this won't work as it's not a dependency that can be injected, it's just a data class that you can instantiate or leave it up to the component.

**Comment by mayurbais** [comment]
yeah, you are right,
I followed the readme first.

added ImageUploadModule to app.module.ts and then ImageUploadModule.forRoot() to import of @NgModule.
added <image-upload> tag to component.html..

then I got this error: 
```
SchoolDetailsDialogComponent.html:1 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'nutsAndScrewsUiGateWayApp.schoolDetails.home.createOrEditLabel'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?
    at viewDebugError (eval at ./node_modules/@angular/core/@angular/core.es5.js (vendor.bundle.js:39), <anonymous>:8638:32)
```


Then I looked at the demo folder of the repository and tried to follow the code in the examples there

**Comment by mayurbais** [comment]
How can I show, please let me know..
I added lib to my project like this : npm install angular2-image-upload --save
I have jhipster app. in my app.module.ts ,
I added this two lines :
import { ImageUploadModule } from 'angular2-image-upload';

and  

ImageUploadModule.forRoot(),

and in one of the component.html ,
I added a 

<image-upload [url]="'my-url.com'"
  [headers]="[
  {name: 'X-XSRF-TOKEN', value: csrfService.getCSRF()}]
  ]"></image-upload>

thats all!

**Comment by UncleDave** [comment]
The module usage looks fine, but the headers are incorrect, they should be:

    [headers]="[
      {header: 'X-XSRF-TOKEN', value: csrfService.getCSRF()}]
    ]"

Other than that I see nothing wrong, if you still have trouble I don't think the issue is this library.

**Comment by lordrip** [comment]
Hi, that is a Angular exception, maybe you're updating a parent component variable in a child component, if that's the case, consider move your variable to a service instead.
