### ISSUE TITLE
custom CSS not working

### ISSUE THREAD

**Issue by tobieeniafe** [aberezkin/ng2-image-upload#134]
I'm trying to customize the button's look to match my UI, but it's not working. Tried changing the core CSS of the module in the `src/image-upload/image-upload.component.css` but its still not working. Also regular format like 
`image-upload label.upload.button {
    background-color: red;
}` 
doesn't work too

**Comment by UncleDave** [comment]
In your own stylesheet please try:

    /deep/ image-upload label.upload.button { background-color: red; }

**Comment by tobieeniafe** [comment]
thanks a lot 👍
