### ISSUE TITLE
Cannot read property 'abort' of undefined

### ISSUE THREAD

**Issue by dinhquyf0** [aberezkin/ng2-image-upload#136]
![image](https://user-images.githubusercontent.com/14790204/30963456-a85b0ba0-a477-11e7-8426-1150a23efb6f.png)
Anyone fix this? please!

**Comment by UncleDave** [comment]
Are you using `beforeUpload`? If so please post your usage.

**Comment by dinhquyf0** [comment]
@UncleDave Yes. I am using beforeUpload
Here is my html file
![image](https://user-images.githubusercontent.com/14790204/31041391-cfc8a074-a5be-11e7-9c99-b14377cb2b03.png)
and here is my typesript file
![image](https://user-images.githubusercontent.com/14790204/31041395-e9b89d22-a5be-11e7-8be2-5cda14b6d1dc.png)

**Comment by dinhquyf0** [comment]
I find my solution and fixed this. just using all source code. :)

**Comment by UncleDave** [comment]
To clarify for anyone else who runs into this: `beforeUpload` has the following signature: `(UploadMetadata) => UploadMetadata | Promise<UploadMetadata>`. Meaning the function you give it is expected to return `UploadMetadata` or `Promise<UploadMetadata>`.
