### ISSUE TITLE
Need to be able to inject Auth Headers into request URL

### ISSUE THREAD

**Issue by flintcreativestudio** [aberezkin/ng2-image-upload#14]
Great module, almost works beautifully out of the box.

Can we somehow find a way to hack our Authorization header into the post request on the service?

Many image upload usage are via logged in users through an API, which requires a token to be passed in the Authorisation header.

**Comment by aberezkin** [comment]
First of all, thank you for such testimonials.

Yeah, I can create an interface for this. I need to find out how auth header should look in a multipart/form-data request.

**Comment by flintcreativestudio** [comment]
Woot! Thanks for the awesome response!
I cloned the new branch, and noticed the folder structure and code structure is different? 
Anyways, I renamed lib folder to src so the paths would get recognised, and also ran " tsc image-upload.component.ts " to compile it to js, but am getting an error on init.

> Uncaught Error: Can't resolve all parameters for ImageUploadComponent: (?).
>     at CompileMetadataResolver.getDependenciesMetadata (http://localhost:4200/main.bundle.js:30279:19)
>     at CompileMetadataResolver.getTypeMetadata (http://localhost:4200/main.bundle.js:30180:26)
>     at CompileMetadataResolver.getDirectiveMetadata (http://localhost:4200/main.bundle.js:29955:28)
>     at http://localhost:4200/main.bundle.js:30024:49
>     at Array.forEach (native)
>     at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/main.bundle.js:30017:44)
>     at http://localhost:4200/main.bundle.js:30005:50
>     at Array.forEach (native)
>     at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/main.bundle.js:29992:44)
>     at RuntimeCompiler._compileComponents (http://localhost:4200/main.bundle.js:43787:47)
>

**Comment by flintcreativestudio** [comment]
Also can you give a little instruction on how to set the headers? Thanks

**Comment by flintcreativestudio** [comment]
Woot, thanks for the awesome response! It works. 
I'm not sure if it could be optimised to be neater, because the standard way to set custom headers is like this:

> let headers = new Headers();
> headers.append('Authorization','Bearer ' + localStorage.getItem('mytoken') );
> 

for the module, I'd have to set it like this in the constructor:

> this.headers = [
  		{
  			header: 'Authorization',
  			value: 'Bearer ' + localStorage.getItem('mytoken')
  		}
  	]

It's just a nitpick though.

Thanks so much, I think you can merge it into master and npm.

**Comment by aberezkin** [comment]
Look, you can add your headers in the HTML attribute like this

```
<image-upload [url]="'my-url.com'"
  [headers]="[
    {header: 'Authorization, vaule: 'Bearer' + localStorage.getItem('mytoken)}
  ]"></image-upload>
```
So you don't need to use anything directly from the library, just use the interface :)

**Comment by aberezkin** [comment]
Feature added to the master branch and published to NPM. Thanks for great proposal :)

**Comment by caglarturkurka** [comment]
Hi, you wrote image tag like this to add header.But this code piece does not work please help me about this problem.Because I want to upload image file with myToken
```
<image-upload [url]="'my-url.com'"
  [headers]="[
    {header: 'Authorization, value: 'Bearer' + localStorage.getItem('mytoken')}
  ]"></image-upload>
```

**Comment by aberezkin** [comment]
@caglarturkurka are there any error logs or it's just don't behave like you expect it to?

**Comment by caglarturkurka** [comment]
my code like this 

```
<image-upload
                  [max]="1"
                  [url]="'localhost:8080/user/photo/upload'"
                  [headers]="[
    {header: 'Authorization, value:' 'Bearer' +uploadPhotoService.getAccount().jwtToken}
  ]"
                ></image-upload>
```


ERROR : 

EXCEPTION: Uncaught (in promise): Error: Directive parse errors:
```
Parser Error: Missing expected } at column 40 in [[
    {header: 'Authorization, value:' 'Bearer' +uploadPhotoService.getAccount().jwtToken}
  ]] in UserAddUpdateComponent@19:18: in Directive DefaultValueAccessor in ./DefaultValueAccessor
Parser Error: Missing expected } at column 40 in [[
    {header: 'Authorization, value:' 'Bearer' +uploadPhotoService.getAccount().jwtToken}
  ]] in UserAddUpdateComponent@19:18: in Directive DefaultValueAccessor in ./DefaultValueAccessor
```

**Comment by caglarturkurka** [comment]
can you help me about adding header with token to upload image

**Comment by caglarturkurka** [comment]
Now I encounter a problem about uploading image

my code like this 

```
<image-upload
                  [url]="'http://localhost:8080/user/photo/upload'"
                  [headers]="[ {header: 'Authorization, value:'+'Bearer '+uploadPhotoService.getAccount().jwtToken + ''} ]"
                ></image-upload>
```

ERROR:
`EXCEPTION: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': 'Authorization, value:Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOIiwiZXhwIjoxNDg2ODE0NTgwfQ.HWapNAN18DOhccCPVlFLRaUpFLqRsaayqnrXhjz0iJNqeSCgHdmfraH57f8RhZD2maCRBP8J28UkzmeCZvfZIA' is not a valid HTTP header field name.`

**Comment by aberezkin** [comment]
Oh, I see. This code is just not valid because of the typo in the README. 
Write the following:
    <image-upload
                  [url]="'http://localhost:8080/user/photo/upload'"
                  [headers]="[ {header: 'Authorization', value: 'Bearer '+uploadPhotoService.getAccount().jwtToken + ''} ]"
                ></image-upload>

The error occurs because of the closing quote. Value is the field of a header object so you need to close quotes after "Authorization". I have a typo in the README so it's my fault, sorry.

**Comment by caglarturkurka** [comment]
Thanks you for your attention.Also I have solved my problem.But also I sent a new problem about angular-cli and ImageUploadModule please check that and please help me about this problem.
