### ISSUE TITLE
Error load angular2-image-upload with SystemJS

### ISSUE THREAD

**Issue by MrHOY** [aberezkin/ng2-image-upload#140]
![screenshot from 2017-10-04 16-21-31](https://user-images.githubusercontent.com/20653706/31168620-2a0b5180-a920-11e7-9377-2c4c6da396c3.png)
My systemjs.config.js

>  paths:{
      'npm:': 'node_modules/'
    },
map: {
      'angular2-image-upload': 'npm:angular2-image-upload'
}
packages: {
      'angular2-image-upload': {
        main: './index.js',
        defaultExtension: 'js'
      }
}

**Comment by UncleDave** [comment]
I guess SystemJS doesn't support ES2015 out of the box, are you not using typescript? Either typescript or babel should be able to transpile it.

**Comment by MrHOY** [comment]
images.githubusercontent.com/20653706/31208707-063180a4-a9b1-11e7-891c-7caa49d1bdd3.png)
I use some package but not see this error, if I use transpiler: "typescript" Angular Bundles not work

![screenshot from 2017-10-05 09-38-36](https://user-

in my file tsconfig.json{

>   "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [ "es2015", "dom" ],
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": true,
    "outDir": "build",
    "skipLibCheck": true
    }
}

**Comment by UncleDave** [comment]
Can you try babel? https://github.com/systemjs/plugin-babel

**Comment by MrHOY** [comment]
It work. Thank you
