### ISSUE TITLE
Events example doesn't set serverResponse attribute properly

### ISSUE THREAD

**Issue by landryraccoon** [aberezkin/ng2-image-upload#142]
The FileHolder class has the definition:

```
export class FileHolder {
  public pending: boolean = false;
  public serverResponse: { status: number, response: any };

  constructor(public src: string, public file: File) {
  }
}
```

However if you try to upload a file to the events example, this is not the shape of the serverResponse object. Instead you will get:

```
{
  "_body": "",
  "status": 200,
  "ok": true,
  "statusText": "OK",
  "headers": {
    "Content-Type": [
      "text\/html; charset=utf-8"
    ]
  },
  "type": 2,
  "url": "https:\/\/httpbin.org\/status\/200"
}
```

Notice that there is no ```response``` attribute, and there is a ```_body``` attribute which is inaccessible in TypeScript (because it is not part of the serverResponse definition) that cannot be used without casting the response to ```any```. This is true even if the body is not empty.

Expected behavior:

events example properly sets the response attribute on serverResponse

or

serverResponse exposes _body attribute as a public attribute (probably renamed to something else).

**Comment by UncleDave** [comment]
Good catch.
