### ISSUE TITLE
Avoid native CSS load

### ISSUE THREAD

**Issue by hmaesta** [aberezkin/ng2-image-upload#146]
Hello.

I noticed that the CSS file of `image-upload` is loaded from `node_modules`.

```javascript
@Component({
  selector: 'image-upload',
  templateUrl: './image-upload.component.html',
  styleUrls: ['./image-upload.component.css']
})
```

I want to use my own stylesheet, so how can I **avoid** that the native CSS is loaded?

I tried `[class]="'myClass'"` but this just add a new class – not remove the native one.

Thank you.

**Comment by UncleDave** [comment]
Currently you can't prevent the CSS from loading, but you can override it as much as you want.
