### ISSUE TITLE
Callback file name

### ISSUE THREAD

**Issue by mmmmyers** [aberezkin/ng2-image-upload#15]
Hi,

Brilliant work. I've successfully added to my project, saving uploaded items to server, but I'm unsure how to access the files / file names.

Could you provide further info on how to get the file / show json response in the (onFileUploadFinish)="imageUploaded($event)" callback?

Many thanks for any help on this!

**Comment by aberezkin** [comment]
Hi, 

Thank you for such testimonials. I glad my library have helped you.

You can easily get file's name in the callback by accessing `event.file.name` field (file field is a `File` object and contains all information about the file not only name). To get the response from your server user `event.serverResponse` it's a string so if you send JSON parse it with `JSON.parse()` and you're good to go. Library was made with this feature in mind. I personally use it to send photos to my server, upload to the Amazon S3 storage and get back image's URL in the client.

**Comment by Mathijs003** [comment]
Hi, 

The name in the callback is the original filename but not the new generated name. 

Any ideas? 

THanks in advance
