### ISSUE TITLE
how resize image height and width

### ISSUE THREAD

**Issue by lakhank143** [aberezkin/ng2-image-upload#150]
hello ,
i am using your angular2-image-upload and i want to resize the uploading image in height or width format or i want to reduce the size of image file like suppose the input file has 1 mb file size it should compress it size upto 500kb at the time of uploading.
please give me some suggestions that how can i implement it in your package

**Comment by UncleDave** [comment]
You can use the `beforeUpload` input to intercept the file and modify it. Perhaps try this with a JS library for image resizing and compression (after a quick google, [here](https://github.com/xkeshi/image-compressor) is one that does compression).


````html
<image-upload [beforeUpload]="onBeforeUpload($event)">
````

````typescript
onBeforeUpload = (metadata: UploadMetadata) => {
  // modifiedFile = Use some library to resize and compress metadata.file
  metadata.file = modifiedFile
  return metadata;
}
````

**Comment by lakhank143** [comment]
i had tried above solution but i am getting one error 'connot find UploadMetadata' . i am using angular2-image-upload plugin of yours. what should i do know

**Comment by UncleDave** [comment]
`import { UploadMetadata } from 'ng2-image-upload'`
