### ISSUE TITLE
remove icon for image 

### ISSUE THREAD

**Issue by tomNjerry** [aberezkin/ng2-image-upload#151]
can we disable or remove close button icon that appear at top of image when uploaded and previewed.

**Comment by hardikpthv** [comment]
hmmm seems that option needs to be added.

**Comment by ABucin** [comment]
This worked for me, though keep in mind that it is a workaround:

```
      .img-ul-container {
        .image {
          .x-mark {
            background: none;

            .close {
              display: none;
            }
          }
        }
      }
```
