### ISSUE TITLE
UploadFiles repeating images multiple times

### ISSUE THREAD

**Issue by skuppa** [aberezkin/ng2-image-upload#153]
The component works great, I added the `uploadedFiles` property then it repeats the uploaded image multiple times, any tips to resolve this issue?  Please see the screenshot, 

Thanks,
-Kuppa

<img width="703" alt="screen shot 2017-11-08 at 12 23 21 pm" src="https://user-images.githubusercontent.com/1365493/32572656-1cc83986-c480-11e7-8d4d-c86a2602c7f6.png">

**Comment by UncleDave** [comment]
May I see your usage? What do you pass to `uploadedFiles`?

**Comment by skuppa** [comment]
Thank you responding quickly. I am able to resolve this issue.  My component had getter method which returns the `uploadFiles` then I changed to property to resolve this issue.

The below code is causing the issue
```
// component.ts
userProfile: UserProfile

ngOnInit() {
  this.userProfile = .. // this will be set by the service via observable response.
}

get uploadFile() {
  return this.service.apiUrl + '/files/' + this.profile.familyPhotoName;
}

get uploadedFiles() {
  return [this.service.apiUrl + '/files/' + this.profile.familyPhotoNam];
}

// in component.html
<image-upload [url]={{uploadFile}} [uploadedFiles]={{uploadedFiles}}></image-upload>
```

I changed the above code as given below to resolve this issue.
```
// component.ts
userProfile: UserProfile
uploadFile: string;
uploadFile: string[]

ngOnInit() {
  this.userProfile = .. // this will be set by the service via observable response.
  this.uploadFile = this.service.apiUrl + '/files/' + this.profile.familyPhotoName;
  this.uploadedFiles = [this.uploadFile];
}

// in component.html
<image-upload [url]={{uploadFile}} [uploadedFiles]={{uploadedFiles}}></image-upload>
```
