### ISSUE TITLE
Parameter 'UploadMetadata' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by TaylorPzreal** [aberezkin/ng2-image-upload#154]
./node_modules/angular2-image-upload/lib/image-upload/image-upload.component.d.ts:22:20
    TS7006: Parameter 'UploadMetadata' implicitly has an 'any' type.

Please fix this shortly. I run build fail every time.
thx very much

**Comment by UncleDave** [comment]
Good spot. I sometimes forget that typescript requires `(name: Type)` for arguments.

**Comment by akkumar** [comment]
Has there been any new release been made incorporating this fix, @UncleDave  ?  ( after 1.0.0-rc.0 , that is )
