### ISSUE TITLE
No Provider For Image Service

### ISSUE THREAD

**Issue by amineparis** [aberezkin/ng2-image-upload#158]
I get this error message. I am using Angular 4

**Comment by UncleDave** [comment]
When you import the module ensure you call `forRoot()`:

`imports: [ ImageUploadModule.forRoot() ]`

**Comment by amineparis** [comment]
I did it. nothing changes

**Comment by UncleDave** [comment]
Please show us the whole error message, and if possible your usage of the library (including the above import).

**Comment by cassianomon** [comment]
Same case, I am using Angular 4, if I import as `ImageUploadModule.forRoot()` I get the error:

`compiler.es5.js:1694 Uncaught Error: Unexpected value '[object Object]' exported by the module SharedModule`

If I import without `.forRoot()` I get `No provider For ImageServer`.

HTML markup:

`<image-upload></image-upload>`

**Comment by aberezkin** [comment]
@cassianomon Which version of angular do you use?

**Comment by cassianomon** [comment]
@aberezkin 4.4.x

**Comment by DarkSmile92** [comment]
Had the same error message. My solution was to import it in the *.module.ts file from the component I am using image-upload and not in the app.module.ts.

Here is my file structure:

```
app.module.ts <- do not import here!
/components
-- /account
-- -- account.module.ts <- import here!
-- -- account.html <- use here
-- -- account.component.ts
```

account.module.ts
```
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { BrowserModule } from '@angular/platform-browser';
import { RouterModule, Routes } from '@angular/router';
import { ImageUploadModule } from "angular2-image-upload";

...

@NgModule({
    imports: [
        FormsModule,
        BrowserModule,
        RouterModule.forChild(accountRoutes),
        ImageUploadModule.forRoot(),
    ],
...
})
export class AccountModule {}

```

Hope this solves your problem as well.

**Comment by UncleDave** [comment]
@DarkSmile92 Does it work if you import `forRoot()` in `app.module.ts` and import without `forRoot()` in the `account.module.ts`?

**Comment by DarkSmile92** [comment]
@UncleDave makes total sense! I just changed my code to import it with `forRoot()` in the `app.module.ts` and the import in `account.module.ts` is now without `forRoot()`.
Works perfectly!
Thanks for the clarification :thumbsup:

**Comment by cassianomon** [comment]
I changed to ng2-img-cropper, can't test atm, thanks for your advice @UncleDave
