### ISSUE TITLE
Support of Angular 5

### ISSUE THREAD

**Issue by someoneNameGrey** [aberezkin/ng2-image-upload#169]
Thanksss!

**Comment by MovGP0** [comment]
I agree that this plugin should be upgraded for Angular 5 support. Current error message: 
```
warning " > angular2-image-upload@1.0.0-rc.0" has incorrect peer dependency "@angular/common@^2.4.9 || ^4.0.0".
warning " > angular2-image-upload@1.0.0-rc.0" has incorrect peer dependency "@angular/core@^2.4.9 || ^4.0.0".
warning " > angular2-image-upload@1.0.0-rc.0" has incorrect peer dependency "@angular/http@^2.4.9 || ^4.0.0".
```

**Comment by dvaughn88** [comment]
Agreed.

**Comment by BenRacicot** [comment]
Hey guys, today I bit the bullet and ported the entire repo over to NG 5.2.1. My hope is that @aberezkin will consider allowing me to commit my changes to a dedicated branch... (NG6?)

For now check it out here at my git: https://github.com/BenRacicot/ng-image-upload
There are a few things to keep in mind for aberezkin's demo stuff... Such as Markdown is now [ngx-md ](https://github.com/dimpu/ngx-md).

My goal was the style scoping issues. Can't seem to figure out how to efficiently override packages scoped styles for production in Angular... Since they're part of the component they add bloat and we would still need to add our own css to them... This situation gets tricky when you're installing a package like this via NPM. Any and all feedback welcome and I hope this helps.

**Comment by hardikpthv** [comment]
Hi all,
I am successfully using this plugin for Angular v5.x.x

**Comment by UncleDave** [comment]
@BenRacicot Pull requests are welcome.

What is your style issue? I know styles can be overridden using `/deep/` (deprecated), or placing styles in your main `styles.(s)css`. As for removing the styles entirely you're right - at the moment it can't be done. The styles weigh in at a whopping 2.7kb so if this is a problem for you I suggest you do what you've already done and fork the repo for your own purposes.

**Comment by BenRacicot** [comment]
Hey @UncleDave! Yes all the shadow piercing selectors are being deprecated and obviously global styles can't apply either. 

So my issue is actually an Angular package issue where it's becoming really difficult to override styles within the shadow DOM. This repo is just an example where we're left with using `::ng-deep` as a temporary fix and also ship the default styles baked into the package. 

I know that 2.7kb is barely anything but I'm in that 10% group that can't ship any kbs that aren't necessary in their production code even though I LOVE your repo. Thanks for all your hard work on this.

**Comment by BenRacicot** [comment]
@UncleDave getting a permission issue when creating a PR (I dont do PR's much)
![image](https://user-images.githubusercontent.com/1815385/35185977-a19eef68-fdda-11e7-86f3-f9bd8e7befa5.png)

**Comment by UncleDave** [comment]
You should be able to create one through Github directly, that's where we usually create pull requests.
Just a note: the repo you linked in this thread is an Angular CLI app (as you say), which works fine for the demo page but you can't really make an angular library with the CLI.

**Comment by BenRacicot** [comment]
Ah, I see. So I think I'm definitely seeing an issue with customizing npm packages for production. I was trying to create a repo where the `image-upload` folder is the package and the demo uses it the same way that a project would.  

image-upload is the main folder, correct? This [stackblitz](https://stackblitz.com/edit/ng-image-upload-base) doesnt seem to allow dropping files though. What am I doing wrong here?

**Comment by UncleDave** [comment]
Well you've flipped the repo structure around, the demo is the main focus of your repo and the library is a subfolder. Whereas in this repo the library is the main focus and the demo is a subfolder.

When this repo gets built it places the output of the library in the dist folder, whereas yours places the output of the demo into the dist folder and the library is a small part of `main.js` or a similar concatenated file.

If you want to make changes to the main repo via a pull request you'll have to fork it and make your changes, while leaving the project structure intact.

Of course you're free to fork it for your own purposes and not pull request it back in.
