### ISSUE TITLE
How can I abort image uploaded event from image uploading event if the file format is not supported?

### ISSUE THREAD

**Issue by Apps-23** [aberezkin/ng2-image-upload#17]

**Comment by aberezkin** [comment]
I'm going to create an interface for format filtering soon. You can't abort uploading from the image uploading event.

**Comment by Apps-23** [comment]
Could you please explain how?
How can I abort imageuploaded to be fired?

**Comment by aberezkin** [comment]
You can't do exactly that with the current build. I suppose you can omit `[url]` directive to disable auto upload and handle uploading (and format filtering) yourself. I'll implement file filtering in 1 or 2 weeks and you will be able to use it with default auto upload, I just don't have time to do it now, sorry.

For now, you can propose criteria to use for filter (e.g. format, size).

**Comment by karolgebert** [comment]
Hi,

any news about this issue?

Regards,
Karol

**Comment by aberezkin** [comment]
You can filter images since #64 is merged.
