### ISSUE TITLE
Support of Angular 6

### ISSUE THREAD

**Issue by furqanaziz** [aberezkin/ng2-image-upload#203]
```
$ ng update @angular/core
                  Package "angular2-image-upload" has an incompatible peer dependency to "rxjs" (requires "^5.0.0-rc.2", would install "6.1.0").
Invalid range: ">=2.3.1 <3.0.0||>=4.0.0"
```

**Comment by tobieeniafe** [comment]
I was gonna open this, then I saw this. I'm trying to update the package to Angular 6 locally and see how it goes. Or did you find a solution for it?

**Comment by furqanaziz** [comment]
@tobieeniafe It is throwing an error I shared above. I have not found a solution yet. Upgrading to Angular 6 with given commands is very difficult there are very high possibility that one of the npm modules in dependency tree will have something wrong in their package.json which will cause an error and you cannot upgrade to 6. I am waiting for now and let's see what happens.

**Comment by tobieeniafe** [comment]
you have to adjust the version values in the dependency's package.json file

**Comment by furqanaziz** [comment]
@tobieeniafe I know it has to be fixed the version values in the dependency's package.json, for that we need too many repos (every repo in the dependency tree have the issue) and fix the package.json and then open PRs and have to wait for owners to merge.

**Comment by tobieeniafe** [comment]
@furqanaziz So I was able to create a file upload manually. Hopefully it'll help.
![screenshot 235](https://user-images.githubusercontent.com/18620774/40555574-7b3dfd0e-6041-11e8-9841-4294442b9158.png)
![screenshot 236](https://user-images.githubusercontent.com/18620774/40555646-b0a1f388-6041-11e8-9621-df1ecb6c2499.png)
![screenshot 237 _li](https://user-images.githubusercontent.com/18620774/40555750-04c11c28-6042-11e8-8031-a623b9209ce0.jpg)

**Comment by RignonNoel** [comment]
@aberezkin : Is it a work in progress ? Do you need some help ?
We can't continue to work with ng4 when ng6 have severals month...

**Comment by tobieeniafe** [comment]
It's done already. It works. But with the imgur API

**Comment by RignonNoel** [comment]
@tobieeniafe I spoked about the issue and not your fix. Actually `ng2-upload-image` doesn't work with ng6 : https://github.com/aberezkin/ng2-image-upload/blob/development/package.json

The actual requirements create an incompatible peer dependency.

**Comment by tobieeniafe** [comment]
Oh yeah it doesn't the packages ng2 depends on have either been removed or compressed in ng6 so it can't work

**Comment by RignonNoel** [comment]
@tobieeniafe This project's have only a few requirements and we need to update it because our clients use it. I just want to know if a guy already work on it or if i need to rampup to fix this project to the latest version of angular

**Comment by tobieeniafe** [comment]
I don't think anyone else has fixed the breaking changes for v6 as at when last I checked

**Comment by radiumrasheed** [comment]
who knows an alternative for this package since we'll not get an update soon
