### ISSUE TITLE
Getting an error when trying to use angular2-image-upload with Angular6 + rxjs 6.0.0

### ISSUE THREAD

**Issue by raynox** [aberezkin/ng2-image-upload#206]
ERROR in node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
node_modules/angular2-image-upload/lib/image-upload/image.service.d.ts(2,10): error TS2305: Module '"/Applications/PhpStorm.app/Contents/bin/~/PhpstormProjects/adverona-seo/node_modules/rxjs/Observable"' has no exported member 'Observable'.

**Comment by binhle410** [comment]
This has nothign to do with this directive

**Comment by enriqueplasencia** [comment]
i have the same error

**Comment by valerioassolari** [comment]
I have the same error. What I do?

**Comment by pavelety** [comment]
Resolves the issue
`npm i rxjs-compat --save`
