### ISSUE TITLE
Support for angular 7

### ISSUE THREAD

**Issue by mauryaak15** [aberezkin/ng2-image-upload#226]
Package "angular2-image-upload" has an incompatible peer dependency to "@angular/common" (requires ">=5.0.0-rc.0 <6.0.0||>=2.4.9 <3.0.0||>=4.0.0 <5.0.0", would install "7.2.2").
                  Package "angular2-image-upload" has an incompatible peer dependency to "@angular/http" (requires ">=5.0.0-rc.0 <6.0.0||>=2.4.9 <3.0.0||>=4.0.0 <5.0.0", would install "7.2.2").
                  Package "angular2-image-upload" has an incompatible peer dependency to "@angular/core" (requires ">=5.0.0-rc.0 <6.0.0||>=2.4.9 <3.0.0||>=4.0.0 <5.0.0", would install "7.2.2").
                  Package "angular2-image-upload" has an incompatible peer dependency to "rxjs" (requires "^5.0.0-rc.2", would install "6.3.3").

**Comment by glen-84** [comment]
Support for Angular 7 was added in `1.0.0-rc.2`.

@aberezkin @UncleDave – when will Angular 8 be supported?

**Comment by UncleDave** [comment]
As far as I'm aware Angular 8 works fine, it just complains about the peer dependency.
