### ISSUE TITLE
How can I have a default image instead of grey background in your tool?

### ISSUE THREAD

**Issue by Apps-23** [aberezkin/ng2-image-upload#24]

**Comment by aberezkin** [comment]
There is no way to use custom styling yet but I'm working on it and to be frank I need help on it because I didn't quite figure out how to give user ability to use custom styles without breaking style encapsulation.

**Comment by Apps-23** [comment]
I was able to do it.
By targetting the div where you had grey background
I used ngClass and used my own background image.

**Comment by aberezkin** [comment]
Can you please provide some code?

**Comment by Apps-23** [comment]
`                   <div class="image-uploader-div" [ngClass]="{'individual-background1': !userData.PhotosModel.IndividualImageUrl1}">
                                <image-upload (onFileUploadFinish)="uploadeImageService.imageUploaded($event,1,userData)" [(ngModel)]="userData.PhotosModel.IndividualImageUrl1" name="photoImageIndividual1" title="Upload" ngDefaultControl></image-upload>
                            </div>`
While I use your component wrapped in a div with ngClass and check if I dont have photo uploaded I use css class individual-background1 so in styles.css I have this class

`.individual-background1 {
    background-image: url('../images/Smile.png');
    background-size: cover;
    background-size: contain;
    background-repeat: round;
}`

**Comment by aquintiliano** [comment]
why did you close? this is a workaround, way far from a real solution for its problem

**Comment by UncleDave** [comment]
Closing in favour of #93
