### ISSUE TITLE
upload to firebase ?

### ISSUE THREAD

**Issue by padrian** [aberezkin/ng2-image-upload#28]
what URL do i use to upload to firebase3, the storage bucket url doesnt seem to work.

Please help,

**Comment by aberezkin** [comment]
Hello, you can provide no URL and use [angularfire2](https://github.com/angular/angularfire2) to upload your images to your firebase storage/

**Comment by padrian** [comment]
how ? any sample code ?

**Comment by joshdobbs** [comment]
@padrian did you find an example of how to do this? I'm looking to achieve the same.

**Comment by padrian** [comment]
hey i just used the normal firebase storage API.

https://firebase.google.com/docs/storage/web/start

https://firebase.google.com/docs/storage/web/upload-files

got through those Sir; all the best.
