### ISSUE TITLE
AOT Fails to compile

### ISSUE THREAD

**Issue by bastarr** [aberezkin/ng2-image-upload#29]
The component is working well except for when I do the AOT compile with following exception: Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable... in node_modules/angular2-image-upload/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken

**Comment by aberezkin** [comment]
Can you show your `package.json`?

**Comment by UncleDave** [comment]
Check [this comment](https://github.com/aberezkin/ng2-image-upload/pull/27#issuecomment-287015541).

**Comment by aberezkin** [comment]
Closed by #30
