### ISSUE TITLE
Disable select button

### ISSUE THREAD

**Issue by ddesna** [aberezkin/ng2-image-upload#33]
I am using custom upload method. It's possible to disable select button while uploading ?

**Comment by aberezkin** [comment]
I can create interface for that.

**Comment by iagocanalejas** [comment]
Any update to this feature, i would like to have it too.

**Comment by nombrekeff** [comment]
@aberezkin disabling button would be nice, I may make a pull request to add that feature

**Comment by aberezkin** [comment]
@nombrekeff It would be nice
