### ISSUE TITLE
Using Angular Http API

### ISSUE THREAD

**Issue by ebondu** [aberezkin/ng2-image-upload#36]
Is there any reason to use XHR  in the image service instead of passing by the Angular Http API? The code should be simplified and the RequestOptionsArgs should be used to pass headers and other options like 'withCredentials'. Moreover, headers / options should also be managed by a user defined http provider.

```javascript
import {Injectable} from "@angular/core";
import {Http, RequestOptionsArgs, Response} from "@angular/http";
import {Observable} from "rxjs/Observable";

export interface Header {
  header: string;
  value: string;
}

@Injectable()
export class ImageService {

  constructor(private http:Http) {}
  public postImage(url: string, image: File, headers?: Header[]): Observable<Response> {
    if (!url || url === '') {
      throw new Error('Url is not set! Please set it before doing queries');
    }

    let options: RequestOptionsArgs = new RequestOptionsArgs();
    if (headers) {
      for (let header of headers)
        options.headers.append(header.header, header.value);
    }

    let formData: FormData = new FormData();
    formData.append('image', image);

    return this.http.post(url, formData, options);
  }
}
```

**Comment by aberezkin** [comment]
Did you test this code?

**Comment by ebondu** [comment]
Yes, I am using it and it seems to works. Of course, the package.json need to be updated to include the angular/http dependency. Another small suggestion, the input name of the FormData should be customized ;).

**Comment by senthilkumar04** [comment]
@aberezkin When will the distribution file of this component be released ? The fixes which has been done are not yet reflected in the production file ?

**Comment by aberezkin** [comment]
@senthilkumar04 I released this today sorry for such a delay
