### ISSUE TITLE
Error when building project

### ISSUE THREAD

**Issue by NightWnvol** [aberezkin/ng2-image-upload#38]
When I try to `ng build -prod` my project this error occurs:

> ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the funct
ion or lambda with a reference to an exported function, resolving symbol Injectable in C:/Users/NightW/Desktop/app-ng2/node_modules/angular2-image-upload/node_
modules/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in C:/Users/NightW/Desktop/app-ng2/node_modules/angular2-image-upload/node_modules/
@angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken in C:/Users/NightW/Desktop/app-ng2/node_modules/angular2-image-upload/node_modules/@angular/c
ore/src/di/opaque_token.d.ts

> ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\Users\NightW\Desktop\app-ng2\src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.t

I updated the dependencies at angular 4.0.0rc.1, could this be the problem?

> "dependencies": {
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/material": "^2.0.0-beta.2",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "angular2-image-upload": "^0.4.1",
    "core-js": "^2.4.1",
    "firebase": "^3.7.3",
    "hammerjs": "^2.0.8",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }

**Comment by UncleDave** [comment]
Update angular2-image-upload to latest.

**Comment by NightWnvol** [comment]
I tried to update it, but it remains to version 0.4.1.
Which command should be used to update to version 0.5.0?

**Comment by NightWnvol** [comment]
Thanks, it works perfectly now.
