### ISSUE TITLE
Error to load component in versions > 0.3.2

### ISSUE THREAD

**Issue by mitin123** [aberezkin/ng2-image-upload#43]
Error: (SystemJS) ctorParameters.map is not a function

**Comment by aberezkin** [comment]
Can't reproduce this

**Comment by mitin123** [comment]
If it can help, here are the dependencies from my package.json
  "dependencies": {
    "@angular/animations": "^4.0.3",
    "@angular/common": "~2.0.2",
    "@angular/compiler": "~2.0.2",
    "@angular/core": "~2.0.2",
    "@angular/forms": "~2.0.2",
    "@angular/http": "~2.0.2",
    "@angular/material": "^2.0.0-beta.3",
    "@angular/platform-browser": "~2.0.2",
    "@angular/platform-browser-dynamic": "~2.0.2",
    "@angular/router": "~3.0.2",
    "@angular/upgrade": "~2.0.2",
    "angular-in-memory-web-api": "~0.1.5",
    "angular2": "^2.0.0-beta.21",
    "angular2-click-to-edit": "^1.0.52",
    "angular2-image-gallery": "^1.0.1",
    "angular2-image-upload": "^0.3.2",
    "angular2-notifications": "^0.4.53",
    "angular2-yandex-maps": "^1.0.34",
    "bootstrap": "^3.3.7",
    "bootstrap-slider": "9.2.0",
    "core-decorators": "^0.15.0",
    "core-js": "^2.4.1",
    "debounce": "^1.0.0",
    "jquery": "3.1.1",
    "ng2-pnotify": "0.0.3",
    "pnotify": "^3.0.0",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.39",
    "web-animations-js": "^2.2.5",
    "zone.js": "^0.6.25"
  },

**Comment by aberezkin** [comment]
Do you still have this issue?
