### ISSUE TITLE
Supported Images ?

### ISSUE THREAD

**Issue by VZnode** [aberezkin/ng2-image-upload#44]
Hi, it would be nice if you add @Input() for supported images in ImageUploadComponent,
because new it accepts all images, even those what are not supported by server, and can lead to some errors.

Now I did little hack, in your component ImageUploadComponent, where ImageUploadComponent.decorators in template property `<div class=\"image-upload\"\n     fileDrop\n     [accept]=\"['image/*']\"` change to `<div class=\"image-upload\"\n     fileDrop\n     [accept]=\"['image/png, image/jpg, image/jpeg']\">` and in `<input\n        type=\"file\"\n        accept=\"image/*"\n ` to `<input\n        type=\"file\"\n        accept=\"image/png, image/jpg, image/jpeg\"\n `,
after that seems to work, but every time I update via npm have to change again.

Thanks :)

**Comment by tarlepp** [comment]
Any progress with this ?

**Comment by aberezkin** [comment]
Closed by #64

**Comment by tarlepp** [comment]
nice!
