### ISSUE TITLE
How do I trigger imageRemoved event by clicking a button

### ISSUE THREAD

**Issue by oluosiname** [aberezkin/ng2-image-upload#45]
After uploading the image, the preview still remains, I'm trying to clear the image after the associated post is submitted(i.e. on click of submit button). I'm new to Angular2, any help would be appreciated

**Comment by aberezkin** [comment]
Okey I can add this feature.

**Comment by akolybelnikov** [comment]
Do we need to create a second button to offset the upload? Right now images go straight into the backend once opened or dragged into the placeholder. This way the preview does not have any functionality: the images remain in the preview and can be removed by clicking them away, but they are already in the database! perhaps binding the upload and the preview removal would be the next logical enhancement.

**Comment by souflam** [comment]
this feature is implemented or not yet ?

**Comment by UncleDave** [comment]
The current API should allow this, yes. An event is raised when the upload completes, and there's a public method to remove an image from the preview.
