### ISSUE TITLE
maxFileSize Bug

### ISSUE THREAD

**Issue by zerox12311** [aberezkin/ng2-image-upload#48]
When I set maxFileSize, then I choose the large picture, which size is  large then i set 
It will show the [fileTooLargeMessage] what i set
But I choose small size picture again, and it will nothing happend.......

**Comment by UncleDave** [comment]
I wasn't able to recreate this: I chose a file that was too large and it rejected it as expected, then I chose an image of the correct size and it uploaded it just fine.
