### ISSUE TITLE
headers json format is incorrect

### ISSUE THREAD

**Issue by EddieLi** [aberezkin/ng2-image-upload#52]
I tried using this format to pass in my authentication token for my node server to process `[headers]="[
    {header: 'Authorization', value: 'MyToken'}
  ]"`

but this json couldn't be read because it's not a valid json. So I changed the format to:
`[headers]='[{"header": "Authorization", "value": "MyToken"}]'`, it seems to work, however, line 29 in file ng2-image-upload/src/image.service.ts is supposed to loop through an array of headers: `for (let header of headers)` except that the variable headers is actually a string in the transpiled js file,
` if (headers) {
            options.headers = new http_1.Headers();
            for (var _i = 0, headers_1 = headers; _i < headers_1.length; _i++) {
                var header = headers_1[_i];
                options.headers.append(header.header, header.value);
            }
        }`
I changed the headers in the for loop to `JSON.parse(headers)` as follows:
` if (headers) {
            options.headers = new http_1.Headers();
            for (var _i = 0, headers_1 = JSON.parse(headers); _i < headers_1.length; _i++) {
                var header = headers_1[_i];
                options.headers.append(header.header, header.value);
            }
        }`

 and the headers directive seems to work properly now.

Anyone has the similar issue?

**Comment by UncleDave** [comment]
I'd try defining it in the component instead, and referencing it in the view.

`headers = [ {header: 'Authorization', value: 'MyToken'} ]`

`[headers]="headers"`

**Comment by EddieLi** [comment]
@UncleDave yes, that should work too! I just you just need to update the wiki to reflect this new format. 
Thanks!

**Comment by UncleDave** [comment]
I tried this in my sandbox project and it worked fine.

`[headers]="[{header: 'auth', value: 'something'}]`
