### ISSUE TITLE
How to get lat/lng from a photo?

### ISSUE THREAD

**Issue by millturnK** [aberezkin/ng2-image-upload#54]
Hi there,
Your module is fantastic, a pleasure to use. This is a question rather than an issue.
I can see a lot of useful attributes in the event class relating to the image file but I need to get the latitude and longitude from the photo.
Just wondering if there was an easy way you could build this functionality in please to allow the image to be queried for its coordinates?
Many thanks,
Katie

**Comment by aberezkin** [comment]
Honestly, I can't understand which coordinates do you mean. Do you want to fetch geopositioning data from the image? 

Can you provide a more detailed explanation?

**Comment by millturnK** [comment]
yes, I mean the latitude and longitude (geoposition) coordinates. For example I am in Canberra, Australia. Let's imagine I live at Parliament House - my latitude (the line of distance which goes vertically through our earth) would be -35.309522 and my longitude (the line going horizontally) 149.123936. If you search Google Maps and enter "-35.309522, 149.123936" in the search bar, it would zoom here. Most of my users won't know the location their photo was taken from which makes it impossible to map, hence I would like to get it automatically from the info they provide. A little bird told me it was encoded into the jpeg object somehow??? Any help would be appreciated and would make a valuable addition to your module for your users such as myself ;-). Might even fork it and add it in ;-).

**Comment by limpep** [comment]
@millturnK This is meta data related to the image. If the information doesn't exist within the image there is no way you can get that information. This meta data would usually be added by the camera which took the image or added later on by a third part service. 

Here are some useful links that might help, 
[How to See Exactly Where a Photo Was Taken (and Keep Your Location Private)](https://www.howtogeek.com/211427/how-to-see-exactly-where-a-photo-was-taken-and-keep-your-location-private/)


Even if you had this meta data within the image you will still have to process this image to extract the meta data by either a third party library or writing a library yourself. 

This library all it does is uploads the image to a specific location.

**Comment by millturnK** [comment]
Thanks for your help, I actually found a great library for parsing EXIF GPS
data from JPEGs (where location data exists) called exif-js (
https://github.com/exif-js/exif-js.git).
