### ISSUE TITLE
Upload Same image

### ISSUE THREAD

**Issue by Karthi-SRV** [aberezkin/ng2-image-upload#55]
While on the below case upload image mot working.

1. Upload a image (single image).
2. Remove that image.
3. Re-upload the same image.

It would upload the same image on second time.

**Comment by Yuki84** [comment]
Friend I had the same problem and I solved it as follows.
 In the input template, where the load functions are, add an ID

<input\n       type=\"file\"\n    name=\"file\"\n id=\"ImageLoad\"\n        accept=\"image/*\"\n             (change)=\"fileChange(input.files)\"\n   #input>\n 

And then in the deleteFile() function add

 var input = document.getElementById("ImageLoad"); 
  input.value = "";

As seen below

 ImageUploadComponent.prototype.deleteFile = function(file) {
        var index = this.files.indexOf(file);
        this.files.splice(index, 1);
        this.fileCounter--;
        this.onRemove.emit(file);

//add this
        var input = document.getElementById("ImageLoad"); 
        input.value = "";
    };

**Comment by aberezkin** [comment]
Do you mean that component should not send second request for same image or what?

**Comment by hungnm92** [comment]
Hi, i have same issue. Can't upload continuity of a image.

1. upload a image: abc.jpg
2. reupload again: abc.jpg (not working, but update image: another.jpg is ok)
