### ISSUE TITLE
How to crope image before upload?

### ISSUE THREAD

**Issue by kolkov** [aberezkin/ng2-image-upload#57]
Hi! Is this possible?
https://github.com/cstefanache/angular2-img-cropper
Or is there a better solution?

**Comment by aberezkin** [comment]
I'm thinking about making some kind of editor for images or using some existing one but I'm not sure how to build that editor in.

**Comment by UncleDave** [comment]
I'd consider this possible with #59, but I won't close if you're still thinking of doing this @aberezkin

**Comment by aberezkin** [comment]
Yeah, I think since #59 is resolved we don't need this feature built in. It could be done with some [other library](https://github.com/cstefanache/angular2-img-cropper) now (I don't quite like ng2-img-cropper btw so we can build our own lib @UncleDave).
