### ISSUE TITLE
Support for css class

### ISSUE THREAD

**Issue by arun-awnics** [aberezkin/ng2-image-upload#58]
Hi @aberezkin First of all, good work. I am planning to use this library in my project and would like to know if you are planning to add features to customize the components. When I say customize, I am talking about styling the component using CSS classes, removing "dropBoxMessage" option, passing the url of the submitted images using onSubmit event to list a few. Will this repository be updated? Can we use it for production purposes?

**Comment by vgogov** [comment]
This would be a good feature. Also for modifying the button.

**Comment by aberezkin** [comment]
@arun-awnics yep I want this feature to be implemented and would be happy if someone can help me with
 this.

**Comment by aberezkin** [comment]
Also, this looks like a generalization of #24.

**Comment by arun-awnics** [comment]
@aberezkin Yes, seems like its similar to #24

**Comment by arun-awnics** [comment]
I will try to work on this if I get enough time but it would be great if you can implement this. Thank you @aberezkin

**Comment by aberezkin** [comment]
I believe that one of the ways to achieve this is to remove css classes incapsulations but I'm not sure that this is the best decision. What do you think?

**Comment by arun-awnics** [comment]
I am not sure on that. I was thinking may be making use of ngClass would solve this problem. @aberezkin

**Comment by UncleDave** [comment]
Closing in favour of #93
