### ISSUE TITLE
Perform action before file upload

### ISSUE THREAD

**Issue by mastarenee** [aberezkin/ng2-image-upload#59]
Is it possible that after the user has selected an image I can call an (onBeforeUpload) function to run edits on the image using ng2-pica. If not can I remove the URL so the file doesn't upload but then after I've performed my edits get your plugin to make a call to the server with a URL I would provide it with?

**Comment by shangab** [comment]
This is very important @mastarenee , for example I have a one PHP back end file to handle uploads of different types of images (Cars, students, ...ect). I want to stash other POST prams to be used in my back end PHP? what can I do?? a call back such as `OnBeforeUpdate ($params)` is very important

**Comment by UncleDave** [comment]
How does the following signature sound:

`onBeforeUpload: (files: FileList) => boolean | FileList | Promise<boolean> | Promise<FileList>`

`onBeforeUpload` will be called when images are selected/dropped, the list of files will be passed into this function. Return a boolean or a promise that resolves to a boolean to continue (true) or abort (false). Alternatively return a modified FileList (or promise) containing the files to continue with.
