### ISSUE TITLE
Error: Supplied parameters do not match any signature of call target.

### ISSUE THREAD

**Issue by HOllarves** [aberezkin/ng2-image-upload#61]
Hi! I'm currently getting this error when trying to build my app for production.

Here is the full error:

`ERROR in /Users/henry_ollarves/webdev/lo-vendo-admin/src/$$_gendir/node_modules/angular2-image-upload/lib/file-drop.directive.ngfactory.ts (51,35): Supplied parameters do not match any signature of call target.
`

Here's my package.json

```
{
  "name": "lo-vendo-admin",
  "version": "1.0.0",
  "description": "Lo Vendo Admin app",
  "author": "Henry Ollarves",
  "theme": "CoreUI",
  "theme-url": "http://coreui.io",
  "license": "MIT",
  "angular-cli": {},
  "engines": {
    "node": "6.10.3",
    "npm": "3.10.10"
  },
  "scripts": {
    "ng": "ng",
    "heroku-prebuild": "npm install -g http-server",
    "heroku-postbuild": "ng build --prod",
    "start": "http-server dist/",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/cli": "1.0.0",
    "@angular/common": "2.4.9",
    "@angular/compiler": "2.4.9",
    "@angular/compiler-cli": "2.4.9",
    "@angular/core": "2.4.9",
    "@angular/forms": "2.4.9",
    "@angular/http": "2.4.9",
    "@angular/platform-browser": "2.4.9",
    "@angular/platform-browser-dynamic": "2.4.9",
    "@angular/router": "3.4.9",
    "@angular/upgrade": "2.4.9",
    "@cloudinary/angular": "^2.1.1",
    "@types/underscore": "^1.8.0",
    "angular2-image-upload": "^0.6.1",
    "angular2-jwt": "^0.2.3",
    "chart.js": "2.5.0",
    "cloudinary-core": "^2.3.0",
    "core-js": "2.4.1",
    "moment": "2.17.1",
    "ng2-bootstrap": "1.4.0",
    "ng2-charts": "1.5.0",
    "rxjs": "5.2.0",
    "ts-helpers": "1.1.2",
    "ts-md5": "^1.2.0",
    "underscore": "^1.8.3",
    "zone.js": "0.7.2"
  },
  "devDependencies": {
    "@types/jasmine": "2.5.45",
    "@types/node": "7.0.8",
    "codelyzer": "2.0.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "3.2.0",
    "karma": "1.5.0",
    "karma-chrome-launcher": "2.0.0",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "karma-coverage-istanbul-reporter": "0.3.0",
    "protractor": "5.1.1",
    "ts-node": "2.1.0",
    "tslint": "4.5.1",
    "typescript": "2.2.1"
  }
}
```

Any ideas what might be causing this? Is it an error with the plugin or with my code? What do you think?

**Comment by UncleDave** [comment]
Sounds like the issue fixed by #53.
Though I would suggest updating your angular to the current version if possible.

**Comment by HOllarves** [comment]
Do you know what's the minimum Angular2 version supported. This app is for one of my clients and since it's going for production I can't use Angular 4. Angular 4 is currently not ready for production, so any help will be kindly appreciated.

**Comment by UncleDave** [comment]
It should be happy with 2.4.9 when #53 gets merged, as that compilation error only appears to pop up for Angular < 4.

I'm curious why you think Angular 4 isn't ready for production? I'm using it in production and haven't had any problems.

**Comment by HOllarves** [comment]
Well according to the Solid Foundation Web Development and I believe the Angular team itself. Check it out: https://solidfoundationwebdev.com/is_it_ready/angular

The again, it appears so because they're still working on it. I'm sure building and deploying an Angular 4 app is completely fine, it's just that some of your code could be deprecated in future versions as the Angular team is still working on it and trying to get it completely right

**Comment by danvelcab** [comment]
Hi. I'm getting the same error. Any solution?  I work with Angular 2.

**Comment by aberezkin** [comment]
Try `0.6.3` everything should be ok now since #53 is merged and published.
