### ISSUE TITLE
[uploaded]

### ISSUE THREAD

**Issue by elyfran** [aberezkin/ng2-image-upload#66]
[uploaded] not work?

**Comment by UncleDave** [comment]
`Uploaded` is not an attribute available on the component, to what are you referring?

**Comment by elyfran** [comment]
i need load imagens server -> client. do u can help me?

I see here : [https://github.com/miklblitz/angular2-image-upload_uploaded](url)

**Comment by UncleDave** [comment]
That is a fork of this repo, any issues should be raised there.

`npm install angular2-image-upload --save` will install THIS version, not the one you're looking for.
