### ISSUE TITLE
Can't bind to 'extensions' since it isn't a known property of 'image-upload'.

### ISSUE THREAD

**Issue by NikasZalias** [aberezkin/ng2-image-upload#68]
I'm getting error "Can't bind to 'extensions' since it isn't a known property of 'image-upload'."

my html looks like that: 
`
<image-upload [max]="1" [buttonCaption]="'Browse'" [preview]="false" [extensions]="['jpg','png','jpeg']" (change)="onFileChange($event)"></image-upload>`

What is the problem??

**Comment by UncleDave** [comment]
Ensure you have the latest version - 0.6.3
