### ISSUE TITLE
Angular cli build error

### ISSUE THREAD

**Issue by janvdt** [aberezkin/ng2-image-upload#71]
Getting a build error when making a build with ng build --prod --aot 
`ERROR in ng:///Users/janvandertaelen/Documents/git/awesome-app/node_modules/angular2-image-upload/lib/image-upload/image-upload.component.d.ts.ImageUploadComponent.html (3,5): Property 'fileCounter' is private and only accessible within class 'ImageUploadComponent'.`

**Comment by UncleDave** [comment]
Just caught this one, will be resolved by #70.
