### ISSUE TITLE
Demo page options

### ISSUE THREAD

**Issue by UncleDave** [aberezkin/ng2-image-upload#73]
I suggest creating a demo website with angular-cli and hosting it on Github pages.

There are multiple ways to go about this:

1. A personal github page at `aberezkin.github.io` - built website must be stored in a repo called `aberezkin.github.io` - this is obviously not very flexible if in the future you decide you want to use that page for yourself.
2. A project github page at `aberezkin.github.io/ng2-image-upload` - built website must be stored in THIS repo under the `docs/` folder. In this case we'd have to build the demo every time it changed and check in the built files.
3. An organisation github page at `ng2-image-upload.github.io` - would have to make a github organization for the project. In this case we could store the demo source code in this project - and create another project `ng2-image-upload/ng2-image-upload.github.io` to contain the built website (can be pushed to quite nicely with a gulp plugin - [example](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/gulpfile.js#L277)).

Of these I think 3 is the cleanest, though I favour option 2 as it's a mixture of clean and easy. Regardless of where we put it I've already started work on a demo site.

Thoughts?

**Comment by aberezkin** [comment]
I think the 2nd case is the best for us :)

**Comment by UncleDave** [comment]
For the changelog I think we should make use of github's releases feature, and also the convention is to have a CHANGELOG.md in the root of the repo.

**Comment by aberezkin** [comment]
Okay then, let me know when I should flick it.
