### ISSUE TITLE
Create changelog

### ISSUE THREAD

**Issue by UncleDave** [aberezkin/ng2-image-upload#74]
Must be done before v1.0.0

**Comment by UncleDave** [comment]
I've been looking into [Conventional Commits](https://conventionalcommits.org/) as a lot of the big boys (angular, aurelia, ng-bootstrap, etc) are using it as a system to automatically generate a changelog and bump their package version.

By using this approach via [Standard Version](https://github.com/conventional-changelog/standard-version) our release process could be as follows:

`npm run release` - `standard-version`
`npm run publish` - `git push --follow-tags origin master; npm publish`

And we'd be done, that would auto-generate a changelog, bump the version number, and publish to npm/push to git.

It's well worth a read and I'd be up for trying it out. Commit messages on branches can still be whatever we like, as long as when the branch is merged it gets squashed into a single commit that is conventional, and any commits to master should be conventional.

**Comment by aberezkin** [comment]
Also, I've thought about creating new `development` branch where we can merge several PRs before merging changes in master and bumping the version. What do you think about it?

**Comment by UncleDave** [comment]
Yes gitflow works for me, master essentially being the production branch.
