### ISSUE TITLE
ng build --prod problem

### ISSUE THREAD

**Issue by Together-Robots** [aberezkin/ng2-image-upload#76]
Hi, when I tried to do a prod build with the newest version of cli, it throws this error.

ERROR in ng:///home/user/Documents/AngularProyects/myApp/node_modules/angular2-image-upload/lib/image-upload/image-upload.component.d.ts.ImageUploadComponent.html (3,5): **Property 'fileCounter' is private and only accessible within class 'ImageUploadComponent'.**

If you guys can change that property it will be awesome! thanks for your time.

**Comment by UncleDave** [comment]
This is fixed in #72, pending release: #70 @aberezkin
