### ISSUE TITLE
Release 0.6.5

### ISSUE THREAD

**Issue by UncleDave** [aberezkin/ng2-image-upload#81]
Try out the new automated changelog and versioning.

I've been having some trouble with npm installing dependencies for `standard-version` incorrectly.
I don't get issues when using yarn instead so I've switched to that:

`npm i -g yarn`

Then `yarn` to install deps, instead of `npm i`

Yarn is quicker and in my experience manages its lock file better than npm. If we agree with using yarn I'll do a cleanup of npm's lock files after this release.

**Comment by UncleDave** [comment]
Hold off until #82 is fixed.

**Comment by UncleDave** [comment]
Good to go.

**Comment by UncleDave** [comment]
Suggested flow for this is:

1. Merge `development` into `master`
2. `npm run release`
3. `npm run publish`
4. Merge `master` into `development`

Not sure we need a pull request for stage 1 as each fix has been individually reviewed, but it might be good practice, thoughts?

**Comment by aberezkin** [comment]
I think that we need to create a PR for 1 to maybe discuss something and check it with Travis for the last time before release.

**Comment by aberezkin** [comment]
So I've published it to the NPM but I've got an error

```
arkadii@arkadii-S551LN:~/Dropbox/OpenSource/ng2-image-upload$ npm run publish

> angular2-image-upload@0.6.5 publish /home/arkadii/Dropbox/OpenSource/ng2-image-upload
> git push --follow-tags origin master && npm publish

Counting objects: 5, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 706 bytes | 0 bytes/s, done.
Total 5 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To git@github.com:aberezkin/ng2-image-upload.git
   6260ee9..1873054  master -> master
 * [new tag]         v0.6.5 -> v0.6.5

> angular2-image-upload@0.6.5 publish .
> git push --follow-tags origin master && npm publish

Everything up-to-date
npm ERR! publish Failed PUT 403
npm ERR! code E403
npm ERR! "You cannot publish over the previously published version 0.6.5." : angular2-image-upload

```

And also, I've found out that I forgot to build it again before publishing. Maybe we will add build step at into `release` script before `standart-version`?

**Comment by UncleDave** [comment]
Ah - I was intending `npm run publish` to bundle the npm publish and the git push, if you don't want to use it like that just unlink them in package.json.

Adding build first seems safe yeah.

**Comment by UncleDave** [comment]
It also looks like the changelog wasn't correctly generated - I'm guessing the squashed commit from dev to master did it. I was assuming that things like `fix()...` in the commit body would work, but maybe it's titles only, oh well - can try again next time.

**Comment by UncleDave** [comment]
FYI - added some documentation via CONTRIBUTING.md and the `publish` script now also runs the build.
