### ISSUE TITLE
drag drop doesn't work

### ISSUE THREAD

**Issue by PaulBravey** [aberezkin/ng2-image-upload#82]
The file drag and drop doesn't work with the default extensions due to the fact that the default is 'image/*'  and then the image-upload.component prefixes that with 'image/' so when you drag a jpeg it compares the file.type 'image/jpeg' with 'image/image/*' and doesn't match

**Comment by PaulBravey** [comment]
Apologies, it does work if you specify [extensions]="['jpeg','png','gif']", it's only not working if you leave it as default.

**Comment by UncleDave** [comment]
You're quite right, good spot.
