### ISSUE TITLE
It would be nice if the clear button called the onRemove event.

### ISSUE THREAD

**Issue by PaulBravey** [aberezkin/ng2-image-upload#84]
If you delete an individual image from the preview then the onRemove event is emitted allowing you to do some cleanup but if you click on the clear button to remove all images no events are emitted making it trickier to do any clean up.

**Comment by UncleDave** [comment]
Agree, should onRemove be called with an array or once for each file?

**Comment by PaulBravey** [comment]
If you're asking me, then the transparent fix is to call it once for each file and leave it to the consumer to automagically batch up any server cleanup calls if they want to. That said, I'd be happy either way.
