### ISSUE TITLE
Style form upload

### ISSUE THREAD

**Issue by tutv95** [aberezkin/ng2-image-upload#9]
How to edit style for the form upload?

**Comment by aberezkin** [comment]
There is no such feature yet, but I definitely want it to be implemented. I just need to figure out how to give the user the opportunity to do custom styles (user defined CSS variables or something different) and keep angular style encapsulation.

If you have some suggestions on how to do it, I would like to hear from you!

**Comment by flintcreativestudio** [comment]
In my case, I had no problems in overriding the styles in the application css file.

Certain styles required an !important attribute though. 
ie.
`.upload-button {
		float: none !important;
		display: block !important;
		text-align: center;
	}`

**Comment by aberezkin** [comment]
@flintcreativestudio 

Did you manage to override for example .image-upload border styles?

**Comment by flintcreativestudio** [comment]
Yes .image-upload borders simply set a css style and it'd override without !important. 
For reference, these were my customizations.

I removed the container border and background color, hid the drag box area, and turned the button into a block element so I could centralise it.

> .image-upload {
> 		border: 0;
> 	}
> 	.file-upload {
> 		background: 0;
> 	}
> 	.drag-box-message {
> 		display: none;	
> 	}
> 	.upload-button {
> 		float: none !important;
> 		display: block !important;
> 		text-align: center;
> 	}
