### ISSUE TITLE
Prefix internal CSS classes & allow apps to pass in custom classes

### ISSUE THREAD

**Issue by UncleDave** [aberezkin/ng2-image-upload#93]
Many of the library's CSS classes are very generic (e.g. `button`) - while angular 2's scoping feature will prevent these classes from interfering with the rest of the application it won't prevent the rest of the application from interfering with the library.

If the implementing application has defined `.button` in a global stylesheet it will cascade down to the library.

Solution: Prefix all of our internal classes with `image-upload__`

**Comment by hardikpthv** [comment]
Yeah this is reasonable to prefix all classes. It would be good if we can shorten the prefix to `img-ul`.

**Comment by aberezkin** [comment]
Would it be useful in #58 and #24? Maybe since our classes are prefixed we can remove angular's style scoping so users can style the component as they want?

**Comment by UncleDave** [comment]
I'd say we accept a `cssClass` input which is added to the component at the highest level - this would allow the user to style every part of it with selectors.

Not that they can't do that already imo, this just makes it a bit clearer.

**Comment by aberezkin** [comment]
Yeah, they do exactly that in [ngx-bootstrap tabs interface](http://valor-software.com/ngx-bootstrap/#/tabs#styling)

**Comment by hardikpthv** [comment]
Will start prefixing the classes first then will begin custom class for buttons and dropbox area.

**Comment by hardikpthv** [comment]
I think we can do something like `customClasses={'buttons':'my-btn-class','dropBox':'my-dropbox-class'}`  as more components(button & dropbox) are there.
