### ISSUE TITLE
Removing images from queue on submit

### ISSUE THREAD

**Issue by mcordell42** [aberezkin/ng2-image-upload#95]
Hello, awesome package! I'm having difficulty figuring out how I would go about removing all the images from the queue when the I click a button. Ideally, I'd like the images to be removed as part of the form submission process, but I can't quite get it. Can you please help?

**Comment by aberezkin** [comment]
We can export `ImageUploadComponent` as a part of #91 so you can use `ImageUploadComponent#deleteAll` on `ViewChild` like so

```
@ViewChild('imageUpload')
private imageUpload: ImageUploadComponent;
...
public onSubmit() {
...
  this.imageUpload.deleteAll()
...
}
```

**Comment by UncleDave** [comment]
Going to close this, if the above method doesn't work for you please reopen.
