### ISSUE TITLE
Directive [extensions] not work on firefox

### ISSUE THREAD

**Issue by mikone** [aberezkin/ng2-image-upload#98]

**Comment by UncleDave** [comment]
Please provide some details - what doesn't work about it? Is there a console error?

**Comment by mikone** [comment]
Sorry,
when i click on the upload button the browser window open with "custom type document" preselected. But the images are not selectable. 
i put [extensions]="['jpg','png','bmp']" directive
Tested on Chrome and work perfectly.
On Firefox not. This is not a bug!!!
Made myself clear? 

Thanks

**Comment by hardikpthv** [comment]
@mikone , can't reproduce the issue with or without `[extensions]` in firefox. It's working fine in Firefox v54.0.1, macOS 10.12.5. Can you please add more details for issue you're facing?

**Comment by UncleDave** [comment]
This also works for me on Firefox 54
![image](https://user-images.githubusercontent.com/3244206/27952035-d360b06c-62fe-11e7-9a7b-214b45cc6842.png)

**Comment by mikone** [comment]
Firefox Version is 54.0.1 on Mac 10.12.5.

```
<image-upload *ngIf="!model.file_path" 
[extensions]="['jpg','png','bmp']" [preview]="false" [hidden]="inUpload" 
[headers]="[{header: 'Cache-Control', value: 'no-cache'}]"
[max]="1" [buttonCaption]="'Upload picture!'" [dropBoxMessage]="'Drop here!'" 
[url]="serverUrl" (onFileUploadFinish)="imageUploaded($event)"
(isPending)="disableSendButton($event)">
</image-upload>
```
<img width="1477" alt="schermata 2017-07-10 alle 10 01 34" src="https://user-images.githubusercontent.com/26596582/28008355-76bdccfe-6557-11e7-9780-6be43b312049.png">

**Comment by UncleDave** [comment]
So that jpg is not selectable? I don't know much about mac.

**Comment by mikone** [comment]
You are right,
i used 'jpeg' instead 'jpg' and now it works.
I'm sorry for that.
Good work
